/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in installed projects and committed here so
// TypeScript has the same baseline before the first local install.
