server:
  port: ${PORT:8080}

spring:
  application:
    name: meowpay
  datasource:
    url: ${SUPABASE_DB_URL:}
    username: ${SUPABASE_DB_USERNAME:}
    password: ${SUPABASE_DB_PASSWORD:}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SUPABASE_JWT_ISSUER:}

app:
  cors:
    allowed-origin: ${CORS_ALLOWED_ORIGIN:http://localhost:3000}
