server:
  port: ${PORT:8080}

spring:
  application:
    name: meowpay
  datasource:
    url: ${SUPABASE_DB_URL:}
    username: ${SUPABASE_DB_USERNAME:}
    password: ${SUPABASE_DB_PASSWORD:}
app:
  security:
    jwt:
      secret: ${SUPABASE_JWT_SECRET:}
      jwk-set-uri: ${SUPABASE_JWT_JWK_SET_URI:}
  cors:
    allowed-origin: ${CORS_ALLOWED_ORIGIN:http://localhost:3000}
